# Generated by Django 4.1.7 on 2023-04-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_order_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='news.ProductOrder', to='news.product'),
        ),
    ]
