# Generated by Django 4.1.7 on 2024-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_uploadfiles_post_author_alter_post_cat_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображения'),
        ),
    ]
