# Generated by Django 4.1.7 on 2024-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_reply_user_reply_author_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
