# Generated by Django 4.1.7 on 2024-02-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_reply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='status',
            new_name='reply_status',
        ),
    ]
