# Generated by Django 4.1.7 on 2023-07-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='auth',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.PROTECT, to='news.author', verbose_name='Автор'),
        ),
    ]
