# Generated by Django 4.1.7 on 2023-06-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_date_news_description_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='post_date',
        ),
    ]
