# Generated by Django 4.1.7 on 2023-06-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name_plural': 'News'},
        ),
    ]
